version: '3'
services:
    nginx:
        build: ./nginx
        ports:
            - '80:80'
        volumes:
            - ../../../../../:/var/www/html
        links:
            - php
        restart: always

    php:
        build: ./php-debug
        volumes:
            - ../../../../../:/var/www/html
        restart: always

    redis:
        image: redis
        ports:
            - '6379:6379'

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.129.0/24
